version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes: 
      - app-data:/var/lib/mysql/data
volumes:
  app-data: